const questions=[{question:'Which practice best protects a password?',answers:['Share it with a classmate','Use a unique, long passphrase','Write it on a public sticky note'],correct:1},{question:'What does HTML primarily provide on a web page?',answers:['Its structure and content','Its internet connection','Its database password'],correct:0},{question:'Which is a helpful first step when testing an interactive project?',answers:['Try the main interaction yourself','Assume it works without opening it','Delete the project files'],correct:0}];
let current=0,started=0,responses=[],answered=false,isComplete=false;
const questionText=document.querySelector('#question-text'),answers=document.querySelector('#answers'),questionCount=document.querySelector('#question-count'),feedback=document.querySelector('#feedback'),nextButton=document.querySelector('#next-button'),completePanel=document.querySelector('#complete-panel'),quizCard=document.querySelector('.quiz-card'),teacherPanel=document.querySelector('#teacher-panel');
function startQuestion(){answered=false;const item=questions[current];questionCount.textContent=`Question ${current+1} of ${questions.length}`;questionText.textContent=item.question;feedback.textContent='';feedback.className='feedback';nextButton.hidden=true;answers.replaceChildren();item.answers.forEach((answer,index)=>{const button=document.createElement('button');button.type='button';button.className='answer-button';button.textContent=answer;button.addEventListener('click',()=>chooseAnswer(index));answers.append(button)});started=performance.now()}
function chooseAnswer(selected){if(answered)return;answered=true;const item=questions[current],seconds=(performance.now()-started)/1000,correct=selected===item.correct;responses.push({question:current+1,answer:item.answers[selected],correct,seconds});[...answers.children].forEach((button,index)=>{button.disabled=true;if(index===item.correct)button.classList.add('correct');else if(index===selected)button.classList.add('incorrect')});feedback.textContent=correct?'Correct — nice work.':`Not quite. The correct answer is: ${item.answers[item.correct]}`;feedback.classList.add(correct?'correct':'incorrect');nextButton.textContent=current===questions.length-1?'Submit responses':'Next question';nextButton.hidden=false;renderTeacher()}
function submit(){isComplete=true;quizCard.hidden=true;completePanel.hidden=false;renderTeacher()}
function renderTeacher(){const correct=responses.filter(item=>item.correct).length,total=responses.reduce((sum,item)=>sum+item.seconds,0),count=responses.length;document.querySelector('#score-summary').textContent=`${correct} / ${count} correct`;document.querySelector('#correct-rate').textContent=count?`${Math.round(correct/count*100)}%`:'—';document.querySelector('#average-time').textContent=count?`${(total/count).toFixed(1)}s`:'—';document.querySelector('#total-time').textContent=count?`${total.toFixed(1)}s`:'—';document.querySelector('#teacher-status').textContent=count===0?'The student has not answered a question yet.':count===questions.length?'Quiz complete. Review the full attempt below.':`The student has answered ${count} of ${questions.length} questions.`;const body=document.querySelector('#results-body');body.replaceChildren();responses.forEach(item=>{const row=document.createElement('tr');row.innerHTML=`<td>${item.question}</td><td>${item.answer}</td><td class="${item.correct?'result-correct':'result-incorrect'}">${item.correct?'Correct':'Incorrect'}</td><td>${item.seconds.toFixed(1)}s</td>`;body.append(row)})}
function showView(view){const student=view==='student';quizCard.hidden=!student||isComplete;completePanel.hidden=!student||!isComplete;teacherPanel.hidden=student;document.querySelector('#view-label').textContent=student?'STUDENT CHECK-IN':'TEACHER DASHBOARD';document.querySelector('#view-description').textContent=student?'Answer three questions. Choose the response that you think is best.':'Switch back to Student at any time. This dashboard updates after every answer.';document.querySelectorAll('.identity-button').forEach(button=>button.classList.toggle('active',button.dataset.view===view));if(!student)renderTeacher()}
nextButton.addEventListener('click',()=>{current+=1;current<questions.length?startQuestion():submit()});document.querySelector('#restart-button').addEventListener('click',()=>{current=0;responses=[];isComplete=false;completePanel.hidden=true;quizCard.hidden=false;startQuestion()});document.querySelector('#reset-button').addEventListener('click',()=>{current=0;responses=[];isComplete=false;completePanel.hidden=true;showView('student');startQuestion()});document.querySelectorAll('.identity-button').forEach(button=>button.addEventListener('click',()=>showView(button.dataset.view)));startQuestion();renderTeacher();
